create table if not exists users
(
    id    bigint generated by default as identity
        primary key,
    email varchar(255) not null
        constraint fk_email
            unique,
    name  varchar(255)
);

create table if not exists item
(
    id          bigint generated by default as identity
        primary key,
    available   boolean,
    description varchar(255),
    name        varchar(255),
    request     bigint,
    owner_id    bigint
        constraint fk_owner_id
            references users
);

create table if not exists booking
(
    id         bigint generated by default as identity
        primary key,
    date_end   timestamp,
    date_start timestamp,
    status     integer,
    booker_id  bigint
        constraint fk_booker_id
            references users,
    item_id    bigint
        constraint fk_booking_item_id
            references item
);

create table if not exists comment
(
    id        bigint generated by default as identity
        primary key,
    created   timestamp,
    text      text,
    author_id bigint
        constraint fk_author_id
            references users,
    item_id   bigint
        constraint fk_comment_item_id
            references item
);



